apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: default
  labels: 
    app: buddha
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
      requests:
        memory: "20Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "200m"
